### ISSUE TITLE
Pages don't reload when redirecting out of modals

### ISSUE THREAD

**Issue by ajdubovoy** [hotwired/hotwire-native-ios#47]
Hi team, first of all congrats on launching v1.0. It's really been a pleasure migrating from the old package. I noticed a small bug I haven't been able to resolve yet in our app that I thought I'd raise an issue about since if might affect others. In our paths, I put something like:

```yml
  -
    patterns:
      - "^/users.*" # Enable to put login screen in a modal
    properties:
      context: modal
      presentation: replace
      pull_to_refresh_enabled: false
```

This works quite well to put out sign-in and sign-up pages (which are managed through `devise`) in a modal. The interface of that feels a bit more "native-ish" than if these pages are just loaded in the inline stack. And it does work _sometimes_.

But frequently, I get an issue where, after successfully signing in, hotwire-native closes the modal totally fine. But if the sign in redirects back to the page that was open _underneath_ the modal, that page doesn't always refresh. Sometimes it does, so I'm a bit confused since the behavior isn't consistent. But it often doesn't.

I'm not 100% sure whether it's a framework error or just me being a more experienced Rails dev than a Swift one. But my instinct is that, if a modal triggers a redirect to a page that's already open under the modal context, that page should always get reloaded, no?

Thanks so much for your help and awesome work on this project!
